name: 02 basics events

on:
  push

jobs:
  print-hello-world:
    runs-on: ubuntu-latest
    steps:
      - name: Print Hello Worled
        run: echo "Hello Worled"
        
      - name: Step2
        run: echo "Hello Worled 2"  
